version: '2'
services:
  web:
    build: .
    environment:
      - NODE_ENV=prod
    ports:
      - "80:8000"
    links:
      - db
  db:
    build: ./db
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: social_tournament
    expose:
        - "3306"
    ports:
      - "3306:3306"